### ISSUE TITLE
SAMSUNG FRAME TV 2020 - APP CHANGE AND TTS NOT WORKING

### ISSUE THREAD

**Issue by pricard32** [jaruba/ha-samsungtv-tizen#124]
The current app are correctly displayed.
Power on/off and volume control working correctly.

I can change from TV to HDMI, but not able to change between TV apps.
The TTS doesnt work for me ?

**Comment by tomredhot** [comment]
Exactly same problem here, with exactly same TV.

**Comment by Surgical71** [comment]
Same Issue here

**Comment by JimboJones3101** [comment]
I've got the same issue that starting apps described in app_list cannot be started.
But maybe some more insights:
I'm running a Samsung 75" QLED 4K Q90TC (2020). I've activated the API (Smartthings) so I'm able to switch to TV, HDMI1, etc, etc. 
Furthermore I'm still able to use the channel-list. 
Nonetheless apps stated in app_list are correctly shown. I mean when I start the netflix app on my TV, Homeassist tells me that the media_player is running org.tizen.netflix-app. After the following configuration it correctly displays "Netflix" with the logo in Home Assist:

```
media_player:
  - platform: samsungtv_tizen
    host: 192.168.178.30
    mac: "zz:zz:zz:zz:zz"
    name: Fernseher
    api_key: "xxx-xxx-xxx"
    device_id: "yyy-yyy-yyy"
    source_list: '{"TV":"KEY_TV","Switch":"ST_HDMI1","Xbox":"ST_HDMI4"}'
    app_list: '{"Netflix": "11101200001/org.tizen.netflix-app", "Prime Video": "3201512006785/org.tizen.primevideo", "YouTube1": "111299001912/9Ur5lzDKqV.TizenYouTube", "YouTube2": "111299001912/9Ur5IzDKqV.TizenYouTube", "Disney+": "3201710015067/MCmYXNxgcu.DisneyPlus"}'
    channel_list: '{"KiKa":"4","MTV":"23"}'
```

Unfortunately its not possible to start the app herefrom. Thats the issue.
As of now the only viable option to start netflix is to keychain commands.
