### ISSUE TITLE
authorisation in loop on TV

### ISSUE THREAD

**Issue by lowrisk75** [jaruba/ha-samsungtv-tizen#132]
I installed your integration,  then I added this to my config :
```
media_player:
  - platform: samsungtv_tizen
    host: 192.168.x.x
    mac: xx:xx:xx:xx:xx:xx

```
didn't work at the beginning, I re-installed the  Samsung TV add-on from the integration (HA) and then I keep getting an authorisation message in loop in my Samsung TV 2020 (QT60 I believe).

every 10 seconds some time less I have 
"
```
HomeAssistant 
You must grant permision for your device to connect to TV.
Allow
Deny 
Close
```
"
