### ISSUE TITLE
Cannot Open Browser Page

### ISSUE THREAD

**Issue by kdeyko** [jaruba/ha-samsungtv-tizen#135]
TV model: UE50TU7170UXRU

Trying to open the browser page from the README example (calling service via Developers Tools):
```yaml
service: media_player.play_media
data:
  entity_id: media_player.bedroom_tv
  media_content_type: "browser"
  media_content_id: "https://www.google.com"
```

And it doesn't work, that is nothing changes on the TV.

Also tried to increase logs (not sure if I did it correctly):
```yaml
logger:
  default: warning
  logs:
    homeassistant.components.media_player: debug
    custom_components.samsungtv_tizen: debug

```
This doesn't help either, nothing new falls in the logs.

Is there a way I can debug it somehow?
