### ISSUE TITLE
is there a way to select applications?

### ISSUE THREAD

**Issue by Smiley-94** [jaruba/ha-samsungtv-tizen#139]
i need to create scripts or swiches for every action of the media player so i can bring them to home kit, i've done some as:
TV_power_on
TV_power_off
tv_volume_up
tv_volume_down
tv_volume_mute
tv_hdmi_1
tv_hdmi_2
but i can't figure out how to select "netflix" for example, 
![media player](https://user-images.githubusercontent.com/56447924/114431300-a0935100-9bbf-11eb-99d9-05354c5cf5c2.png)
i want to create scripts to select those options, is it possible?

**Comment by funkyfisch** [comment]
You can do this by calling the following service:

![image](https://user-images.githubusercontent.com/4956573/117966106-d5600880-b323-11eb-81d2-8c25f38dbd14.png)

**Comment by Smiley-94** [comment]
i solved it by using a similar code:

```
service: media_player.select_source
target:
  entity_id: media_player.samsung_tv_tizen
data:
  source: Netflix
```
