### ISSUE TITLE
HA not start when integration set

### ISSUE THREAD

**Issue by miquellaboria** [jaruba/ha-samsungtv-tizen#146]
Today I set the integration. 

My Config:

```
media_player:
  - platform: samsungtv_tizen
    name: “Q900R”
    api_key: "xxx"
    device_id: "xxx" 
```

On start log shows:
_2021-05-17 17:33:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration samsungtv_tizen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant_

But HA doesn't start... I have to remove Config lines and restart to HA returns to work...

Any help is apreciated!
Thanks!
