### ISSUE TITLE
Not able to stream camera to TV

### ISSUE THREAD

**Issue by avico78** [jaruba/ha-samsungtv-tizen#193]
HA version:2022.11.3
samsung tizen v: 1.6.1
TV Samsung Q90 (2021 model)

Problem: not able to cast/stream camera to the TV

```
service: camera.play_stream
data:
  media_player: media_player.samsung_tv
target:
  entity_id: camera.intercom_camera

```
Also tried:

```
  service: camera.play_stream
  target:
    entity_id: camera.intercom_camera
  data:
    media_player: media_player.samsung_tv
```
for both getting:
```

2022-11-19 14:08:04.137 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for samsungtv_tizen doing blocking calls at custom_components/samsungtv_tizen/websockets.py, line 115: time.sleep(self.key_press_delay)

```
