### ISSUE TITLE
NU8000 not working anymore

### ISSUE THREAD

**Issue by fi-sch** [jaruba/ha-samsungtv-tizen#20]
Hi!

After last update (v1.3.3) I can successfully setup my NU8000 TV, ping works as well. The problem is that the only thing I can control is device volume via slider/knob. Even 'vol +/-' or 'on/off' buttons does not work. No errors in log.

Heres my config:
```
media_player:
  - platform: samsungtv_custom
    host: 192.168.8.166
    port: 8002
    mac: !secret mac_samsung
    update_method: "ping"
    source_list: '{"TV": "KEY_TV", "HDMI": "KEY_HDMI"}'
    app_list: '{"Netflix": "11101200001","YouTube": "111299001912","Internet": "org.tizen.browser"}'
```

Just to be clear. Everything was working as intended before this update. Even though I did not have 'app_list' set up at that time.
Any ideas?

EDIT: Surprisingly play_media service works really well. Too bad I cannot turn on/off my TV, even manually via proper service. It would be so perfect if I could.
