### ISSUE TITLE
media_player / device doesn't appear in Home Assistant

### ISSUE THREAD

**Issue by ReflexReaction** [jaruba/ha-samsungtv-tizen#203]
Running Home Assistant in Docker on a Synology DS220+.  Have installed HACS and it appears in HA menus etc.

Below snippet from my configuration.yaml:

```
media_player:
  - platform: samsungtv_tizen
   host: 192.168.x.x
    mac: xxxxx
    name: Samsung Frame 50
    api_key: "xxxx"
    device_id: "xxxx"
    source_list: [
        {"name": "Switch", "type": "input", "value": "HDMI1"},
        {"name": "FireStick TV", "type": "input", "value": "HDMI3"}
    ]
```

When launching Home Assistant, I get the following error:  

> Invalid config for [media_player.samsungtv_tizen]: value should be a string for dictionary value @ data['source_list']. Got [OrderedDict([('name', 'FireStick TV'), ('type', 'input'), ('value', 'HDMI3')])]. (See /config/configuration.yaml, line 17). Please check the docs at https://github.com/jaruba/ha-samsungtv-tizen

What have I done wrong? Clearly I am not setting source_list correctly, but I can't work out how to do it and it's not clear from the readme (sorry!)
