### ISSUE TITLE
My TV is displayed as unnamed_device

### ISSUE THREAD

**Issue by denysdovhan** [jaruba/ha-samsungtv-tizen#52]
Here's my config from `configuration.yaml`:

```yaml
media_player:
  - platform: samsungtv_tizen
    name: Samsung TV
    host: 192.168.0.XXX
    port: 8002
    mac: XX:XX:XX:XX:XX:XX
    api_key: "XXXXXX"
    device_id: "XXXXXX"
    source_list: >-
      {
        "Apple TV": "ST_HDMI1",
        "PlayStation 4": "ST_HDMI2"
      }
    app_list: >-
      {
        "Netflix": "11101200001",
        "YouTube": "111299001912"
        "Internet": "org.tizen.browser"
      }
```

However, I have two entities that mirror each other: `media_player.samsung_tv` and `media_player.unnamed_device`.

![image](https://user-images.githubusercontent.com/3459374/78504944-c732d680-7778-11ea-8baf-17b6a3084eff.png)

Home Assistant also says my TV's entity does not have a unique ID.

![image](https://user-images.githubusercontent.com/3459374/78505007-21cc3280-7779-11ea-88d0-31040beaabdf.png)

How can I set up my TV properly and get rid of `unnamed_device`?
