### ISSUE TITLE
how can you add multiple media players to this?

### ISSUE THREAD

**Issue by DanielPiccoli** [jaruba/ha-samsungtv-tizen#57]
media_player:
  - platform: samsungtv_tizen
    name: TV1
    host: 10.0.0.51
    port: 8002
    mac: xxxxxxxxxxxxxxx

this works fine, i can see the card.
but i have 4 other samsung TVs that i`d like o control using this? how do i set it up ?

**Comment by jaruba** [comment]
```
media_player:
  - platform: samsungtv_tizen
    name: TV1
    host: 10.0.0.51
    port: 8002
    mac: xxxxxxxxxxxxxxx
  - platform: samsungtv_tizen
    name: TV2
    host: 10.0.0.52
    port: 8002
    mac: xxxxxxxxxxxxxxx
```
